### ISSUE TITLE
bouncebacks I got

### ISSUE THREAD

**Issue by nataliamush** [alandgton/activism-mailbot#1]
Thanks so much for this. Just reporting back on how things went for me:

1) 
Message blocked
--
Your message to Katherine.G.Richardson@phila.gov has been blocked. See technical details below for more information.

2) 

Richard N. Gottfried gottfriedr@nyassembly.gov auto-reply includes this info: **If your e-mail did not include your postal address, please re-send it with that information.
**If the issue that you wrote about is a federal matter, I urge you to contact your U.S. Representative and our U.S. Senators. 
(so maybe some location fill-in is useful? especially because a few of the emails that were sent said "as a concerned constituent" for places I am not a constituent of)

3) 

Your message to Abdi.Warsame@minneapolismn.gov couldn't be delivered.
--
A custom mail flow rule created by an admin at minneapolismngov.onmicrosoft.com has blocked your message.

**Comment by alandgton** [comment]
Thanks natalia! I've removed invalid emails and I'm working on a fix to select which officials you email by location.
