### ISSUE TITLE
feat: add support for windows users

### ISSUE THREAD

**Issue by cvaldez98** [alandgton/activism-mailbot#4]

**Comment by alandgton** [comment]
the application has been containerized 

could you let me know if it works on windows?

**Comment by cvaldez98** [comment]
@darrylbalderas could you confirm? I don't generally use windows.

**Comment by BMariscal** [comment]
I'm unfortunately currently on a Windows laptop (begrudgingly). To get Docker running on windows you have to set up Docker Toolbox. 
Steps here:
https://docs.docker.com/toolbox/toolbox_install_windows/

I'll update the Readme.md with this info. 

@cvaldez98 @alandgton The containerized program worked for me on Windows. Everything looks good! You can close this ticket.
