### ISSUE TITLE
Use f-string formatting instead of %-formatting

### ISSUE THREAD

**Issue by BMariscal** [alandgton/activism-mailbot#6]
f-strings are faster than %-formatting because f-strings are expressions evaluated at runtime rather than constant values.

https://www.python.org/dev/peps/pep-0498/#abstract

**Comment by alandgton** [comment]
thanks Brie! that was a really interesting read and i've pushed a [commit to switch away from %-formatting ](https://github.com/alandgton/activism-mailbot/commit/da4f366cedb358e85f367e428569ef631ec1219c)
