### ISSUE TITLE
Dockerize to avoid having to come up with installation instructions for every OS

### ISSUE THREAD

**Issue by BMariscal** [alandgton/activism-mailbot#8]
https://docker-curriculum.com/

**Comment by alandgton** [comment]
the script now can run in a container, could you take a look and let me know what you think?

**Comment by BMariscal** [comment]
I'm sorry, I just saw this @alandgton. I'll take a look!

**Comment by BMariscal** [comment]
@alandgton It looks good. Thanks for letting me know.
